"""
Loads the BEST dispatch table from a private binary or environment variable.

Priority:
  1. MONOGATE_ROUTING env var — JSON object: {"exp": "EML", "ln": "EXL", ...}
  2. _routing.pkl alongside this file — pickle of the same dict shape
  3. None — caller falls back to EML-for-everything

The binary is generated by scripts/compile_routing.py from the private source
file _routing_private.py (not tracked in the public repo).
"""

from __future__ import annotations

import json
import os
import pickle
from pathlib import Path
from typing import Optional


def _load_routing_names() -> Optional[dict[str, str]]:
    """Return {op_name: operator_name} or None if no private config is available."""

    env = os.environ.get("MONOGATE_ROUTING")
    if env:
        try:
            table = json.loads(env)
            if isinstance(table, dict):
                return {str(k): str(v) for k, v in table.items()}
        except (json.JSONDecodeError, TypeError, ValueError):
            pass

    bin_path = Path(__file__).parent / "_routing.pkl"
    if bin_path.exists():
        try:
            with bin_path.open("rb") as fh:
                table = pickle.load(fh)  # noqa: S301 — trusted internal binary
            if isinstance(table, dict):
                return {str(k): str(v) for k, v in table.items()}
        except Exception:
            pass

    return None
