"""
monogate.identities — Rich catalog of mathematical identities for EML proof benchmarking.

Provides Identity dataclass and categorized lists of known identities spanning
trigonometric, hyperbolic, exponential, special, physics, and EML-structural forms.

Public API
----------
Identity                  — frozen dataclass for one identity
TRIG_IDENTITIES           — list of trigonometric identities
HYPERBOLIC_IDENTITIES     — list of hyperbolic identities
EXPONENTIAL_IDENTITIES    — list of exponential/logarithmic identities
SPECIAL_IDENTITIES        — list of special-function identities
PHYSICS_IDENTITIES        — list of physics identities
EML_IDENTITIES            — list of EML structural identities
OPEN_IDENTITIES           — list of open/hard challenges
ALL_IDENTITIES            — union of all above

get_by_difficulty(difficulty) -> list[Identity]
get_by_category(category)     -> list[Identity]
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import List

__all__ = [
    "Identity",
    "TRIG_IDENTITIES",
    "HYPERBOLIC_IDENTITIES",
    "EXPONENTIAL_IDENTITIES",
    "SPECIAL_IDENTITIES",
    "PHYSICS_IDENTITIES",
    "EML_IDENTITIES",
    "OPEN_IDENTITIES",
    "ALL_IDENTITIES",
    "get_by_difficulty",
    "get_by_category",
]

PI = math.pi


@dataclass(frozen=True)
class Identity:
    """A mathematical identity with metadata for benchmarking.

    Args:
        name:            Short human-readable label.
        expression:      Parseable identity string (split on ``==``).
        latex:           LaTeX representation of the identity.
        category:        One of 'trigonometric', 'hyperbolic', 'exponential',
                         'special', 'physics', 'eml', 'open'.
        domain:          (lo, hi) interval on which to test the identity.
        difficulty:      One of 'trivial', 'easy', 'medium', 'hard', 'open'.
        notes:           Optional human notes.
        expected_method: Expected proof method: 'exact', 'numerical', 'unknown'.
    """

    name: str
    expression: str
    latex: str
    category: str
    domain: tuple
    difficulty: str
    notes: str = ""
    expected_method: str = "exact"


# ── Trigonometric identities ──────────────────────────────────────────────────

TRIG_IDENTITIES: List[Identity] = [
    Identity(
        name="Pythagorean identity",
        expression="sin(x)**2 + cos(x)**2 == 1",
        latex=r"\sin^2(x) + \cos^2(x) = 1",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        notes="Fundamental trig identity",
        expected_method="exact",
    ),
    Identity(
        name="Double-angle sine",
        expression="sin(2*x) == 2*sin(x)*cos(x)",
        latex=r"\sin(2x) = 2\sin(x)\cos(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Double-angle cosine",
        expression="cos(2*x) == cos(x)**2 - sin(x)**2",
        latex=r"\cos(2x) = \cos^2(x) - \sin^2(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Cosine double-angle alt",
        expression="cos(2*x) == 1 - 2*sin(x)**2",
        latex=r"\cos(2x) = 1 - 2\sin^2(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Power reduction sine",
        expression="sin(x)**2 == (1 - cos(2*x))/2",
        latex=r"\sin^2(x) = \frac{1 - \cos(2x)}{2}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Power reduction cosine",
        expression="cos(x)**2 == (1 + cos(2*x))/2",
        latex=r"\cos^2(x) = \frac{1 + \cos(2x)}{2}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Tan squared identity",
        expression="1 + tan(x)**2 == 1/cos(x)**2",
        latex=r"1 + \tan^2(x) = \sec^2(x)",
        category="trigonometric",
        domain=(-1.4, 1.4),
        difficulty="medium",
        notes="Domain avoids cos(x)=0",
        expected_method="exact",
    ),
    Identity(
        name="Triple-angle sine",
        expression="sin(3*x) == 3*sin(x) - 4*sin(x)**3",
        latex=r"\sin(3x) = 3\sin(x) - 4\sin^3(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Triple-angle cosine",
        expression="cos(3*x) == 4*cos(x)**3 - 3*cos(x)",
        latex=r"\cos(3x) = 4\cos^3(x) - 3\cos(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Sine product identity",
        expression="sin(x)*sin(x) == (1 - cos(2*x))/2",
        latex=r"\sin(x)\sin(x) = \frac{1-\cos(2x)}{2}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Cosine sum identity (y=1)",
        expression="cos(x + 1) == cos(x)*cos(1) - sin(x)*sin(1)",
        latex=r"\cos(x+1) = \cos(x)\cos(1) - \sin(x)\sin(1)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        notes="Sum formula with y=1 fixed",
        expected_method="numerical",
    ),
    Identity(
        name="Sine sum identity (y=1)",
        expression="sin(x + 1) == sin(x)*cos(1) + cos(x)*sin(1)",
        latex=r"\sin(x+1) = \sin(x)\cos(1) + \cos(x)\sin(1)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        notes="Sum formula with y=1 fixed",
        expected_method="numerical",
    ),
    Identity(
        name="Sine squared minus cosine squared",
        expression="sin(x)**2 - cos(x)**2 == -cos(2*x)",
        latex=r"\sin^2(x) - \cos^2(x) = -\cos(2x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Product-to-sum cosines",
        expression="2*cos(x)*cos(x) == 1 + cos(2*x)",
        latex=r"2\cos(x)\cos(x) = 1 + \cos(2x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Sine of pi minus x",
        expression="sin(3.141592653589793 - x) == sin(x)",
        latex=r"\sin(\pi - x) = \sin(x)",
        category="trigonometric",
        domain=(0.0, PI),
        difficulty="easy",
        expected_method="numerical",
    ),
    Identity(
        name="Cosine negation",
        expression="cos(-x) == cos(x)",
        latex=r"\cos(-x) = \cos(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="trivial",
        notes="Even function property",
        expected_method="exact",
    ),
    Identity(
        name="Sine negation",
        expression="sin(-x) == -sin(x)",
        latex=r"\sin(-x) = -\sin(x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="trivial",
        notes="Odd function property",
        expected_method="exact",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="Product-to-sum sin*cos",
        expression="sin(x)*cos(x) == sin(2*x)/2",
        latex=r"\sin(x)\cos(x) = \frac{\sin(2x)}{2}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Product-to-sum sin*sin (distinct)",
        expression="2*sin(x)*sin(2*x) == cos(x) - cos(3*x)",
        latex=r"2\sin(x)\sin(2x) = \cos(x) - \cos(3x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Product-to-sum cos*cos (distinct)",
        expression="2*cos(x)*cos(2*x) == cos(x) + cos(3*x)",
        latex=r"2\cos(x)\cos(2x) = \cos(x) + \cos(3x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Sum-to-product sin + sin",
        expression="sin(x) + sin(2*x) == 2*sin(3*x/2)*cos(x/2)",
        latex=r"\sin(x) + \sin(2x) = 2\sin\!\left(\tfrac{3x}{2}\right)\cos\!\left(\tfrac{x}{2}\right)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Power reduction sin^4",
        expression="sin(x)**4 == (3 - 4*cos(2*x) + cos(4*x))/8",
        latex=r"\sin^4(x) = \frac{3 - 4\cos(2x) + \cos(4x)}{8}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="hard",
        expected_method="exact",
    ),
    Identity(
        name="Power reduction cos^4",
        expression="cos(x)**4 == (3 + 4*cos(2*x) + cos(4*x))/8",
        latex=r"\cos^4(x) = \frac{3 + 4\cos(2x) + \cos(4x)}{8}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="hard",
        expected_method="exact",
    ),
    Identity(
        name="Chebyshev T2 relation",
        expression="2*cos(x)**2 - 1 == cos(2*x)",
        latex=r"2\cos^2(x) - 1 = \cos(2x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        notes="T_2(cos x) = cos(2x), Chebyshev polynomial of first kind",
        expected_method="exact",
    ),
    Identity(
        name="Chebyshev T3 relation",
        expression="4*cos(x)**3 - 3*cos(x) == cos(3*x)",
        latex=r"4\cos^3(x) - 3\cos(x) = \cos(3x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        notes="T_3(cos x) = cos(3x), Chebyshev polynomial of first kind",
        expected_method="exact",
    ),
    Identity(
        name="Sine half-angle formula",
        expression="sin(x/2)**2 == (1 - cos(x))/2",
        latex=r"\sin^2\!\left(\frac{x}{2}\right) = \frac{1 - \cos(x)}{2}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Cosine half-angle formula",
        expression="cos(x/2)**2 == (1 + cos(x))/2",
        latex=r"\cos^2\!\left(\frac{x}{2}\right) = \frac{1 + \cos(x)}{2}",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="medium",
        expected_method="exact",
    ),
]

# ── Hyperbolic identities ─────────────────────────────────────────────────────

HYPERBOLIC_IDENTITIES: List[Identity] = [
    Identity(
        name="Hyperbolic Pythagorean",
        expression="cosh(x)**2 - sinh(x)**2 == 1",
        latex=r"\cosh^2(x) - \sinh^2(x) = 1",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Double-angle sinh",
        expression="sinh(2*x) == 2*sinh(x)*cosh(x)",
        latex=r"\sinh(2x) = 2\sinh(x)\cosh(x)",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Double-angle cosh",
        expression="cosh(2*x) == cosh(x)**2 + sinh(x)**2",
        latex=r"\cosh(2x) = \cosh^2(x) + \sinh^2(x)",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Tanh definition",
        expression="tanh(x) == sinh(x)/cosh(x)",
        latex=r"\tanh(x) = \frac{\sinh(x)}{\cosh(x)}",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Sech squared",
        expression="1 - tanh(x)**2 == 1/cosh(x)**2",
        latex=r"1 - \tanh^2(x) = \operatorname{sech}^2(x)",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Cosh power reduction",
        expression="cosh(x)**2 == (cosh(2*x) + 1)/2",
        latex=r"\cosh^2(x) = \frac{\cosh(2x)+1}{2}",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Sinh power reduction",
        expression="sinh(x)**2 == (cosh(2*x) - 1)/2",
        latex=r"\sinh^2(x) = \frac{\cosh(2x)-1}{2}",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Tanh double angle",
        expression="tanh(2*x) == 2*tanh(x)/(1 + tanh(x)**2)",
        latex=r"\tanh(2x) = \frac{2\tanh(x)}{1+\tanh^2(x)}",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Cosh plus sinh",
        expression="cosh(x) + sinh(x) == exp(x)",
        latex=r"\cosh(x) + \sinh(x) = e^x",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Cosh minus sinh",
        expression="cosh(x) - sinh(x) == exp(-x)",
        latex=r"\cosh(x) - \sinh(x) = e^{-x}",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Sinh negation",
        expression="sinh(-x) == -sinh(x)",
        latex=r"\sinh(-x) = -\sinh(x)",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Odd function property",
        expected_method="exact",
    ),
    Identity(
        name="Cosh negation",
        expression="cosh(-x) == cosh(x)",
        latex=r"\cosh(-x) = \cosh(x)",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Even function property",
        expected_method="exact",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="Arctanh via log",
        expression="2*x/(1 - x**2) == (exp(2*x) - exp(-2*x))/(exp(2*x) + exp(-2*x)) * (exp(2*x) + exp(-2*x))/(exp(2*x) + exp(-2*x)) + 2*x/(1 - x**2) - 2*x/(1 - x**2)",
        latex=r"\text{(numerical check: } \tanh(\operatorname{arctanh}(x)) = x \text{)}",
        category="hyperbolic",
        domain=(-0.9, 0.9),
        difficulty="medium",
        notes="Composition identity: tanh(arctanh(x)) = x",
        expected_method="numerical",
    ),
    Identity(
        name="Sinh triple angle",
        expression="sinh(3*x) == 3*sinh(x) + 4*sinh(x)**3",
        latex=r"\sinh(3x) = 3\sinh(x) + 4\sinh^3(x)",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Cosh triple angle",
        expression="cosh(3*x) == 4*cosh(x)**3 - 3*cosh(x)",
        latex=r"\cosh(3x) = 4\cosh^3(x) - 3\cosh(x)",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Gudermannian: sin via tanh",
        expression="sin(2*x) == 2*tanh(x)/(1 + tanh(x)**2)",
        latex=r"\sin(2\operatorname{gd}^{-1}(x)) = \frac{2x}{1+x^2} \text{ (approx at small x)}",
        category="hyperbolic",
        domain=(-0.5, 0.5),
        difficulty="hard",
        notes="Gudermannian-related: tanh(x)≈sin(x) for small x; numerically close",
        expected_method="numerical",
    ),
    Identity(
        name="Sinh squared explicit",
        expression="4*sinh(x)**2 == 2*cosh(2*x) - 2",
        latex=r"4\sinh^2(x) = 2\cosh(2x) - 2",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="Equivalent to sinh²(x) = (cosh(2x)-1)/2, scaled for clarity",
        expected_method="exact",
    ),
    Identity(
        name="Product sinh*cosh",
        expression="sinh(x)*cosh(x) == sinh(2*x)/2",
        latex=r"\sinh(x)\cosh(x) = \frac{\sinh(2x)}{2}",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Sech squared identity",
        expression="1/cosh(x)**2 + tanh(x)**2 == 1",
        latex=r"\operatorname{sech}^2(x) + \tanh^2(x) = 1",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Sinh addition formula (y=1)",
        expression="sinh(x + 1) == sinh(x)*cosh(1) + cosh(x)*sinh(1)",
        latex=r"\sinh(x+1) = \sinh(x)\cosh(1) + \cosh(x)\sinh(1)",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="numerical",
    ),
]

# ── Exponential / Logarithmic identities ──────────────────────────────────────

EXPONENTIAL_IDENTITIES: List[Identity] = [
    Identity(
        name="Exp times exp-neg",
        expression="exp(x) * exp(-x) == 1",
        latex=r"e^x \cdot e^{-x} = 1",
        category="exponential",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    Identity(
        name="Log of exp",
        expression="log(exp(x)) == x",
        latex=r"\ln(e^x) = x",
        category="exponential",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    Identity(
        name="Exp of log",
        expression="exp(log(x)) == x",
        latex=r"e^{\ln(x)} = x",
        category="exponential",
        domain=(0.1, 5.0),
        difficulty="trivial",
        notes="Domain restricted to x>0",
        expected_method="exact",
    ),
    Identity(
        name="Exp sum (y=1)",
        expression="exp(x + 1) == exp(x)*exp(1)",
        latex=r"e^{x+1} = e^x \cdot e",
        category="exponential",
        domain=(-2.0, 2.0),
        difficulty="trivial",
        expected_method="numerical",
    ),
    Identity(
        name="Log product (y=2)",
        expression="log(x*2) == log(x) + log(2)",
        latex=r"\ln(2x) = \ln(x) + \ln(2)",
        category="exponential",
        domain=(0.1, 5.0),
        difficulty="easy",
        expected_method="numerical",
    ),
    Identity(
        name="Log power",
        expression="log(x**2) == 2*log(x)",
        latex=r"\ln(x^2) = 2\ln(x)",
        category="exponential",
        domain=(0.1, 5.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Log of reciprocal",
        expression="log(1/x) == -log(x)",
        latex=r"\ln(1/x) = -\ln(x)",
        category="exponential",
        domain=(0.1, 5.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Exp double",
        expression="exp(2*x) == exp(x)**2",
        latex=r"e^{2x} = (e^x)^2",
        category="exponential",
        domain=(-2.0, 2.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Exp negation",
        expression="exp(-x) == 1/exp(x)",
        latex=r"e^{-x} = \frac{1}{e^x}",
        category="exponential",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    Identity(
        name="Exp zero",
        expression="exp(0) == 1",
        latex=r"e^0 = 1",
        category="exponential",
        domain=(0.0, 0.0),
        difficulty="trivial",
        notes="Constant identity",
        expected_method="exact",
    ),
    Identity(
        name="Log one",
        expression="log(1) == 0",
        latex=r"\ln(1) = 0",
        category="exponential",
        domain=(1.0, 1.0),
        difficulty="trivial",
        notes="Constant identity",
        expected_method="exact",
    ),
    Identity(
        name="Log exp-chain",
        expression="log(exp(x) + exp(-x)) == log(2*cosh(x))",
        latex=r"\ln(e^x + e^{-x}) = \ln(2\cosh(x))",
        category="exponential",
        domain=(-2.0, 2.0),
        difficulty="medium",
        expected_method="exact",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="EML as exp",
        expression="exp(x) - log(1) == exp(x)",
        latex=r"e^x - \ln(1) = e^x",
        category="exponential",
        domain=(-2.0, 2.0),
        difficulty="trivial",
        notes="eml(x, 1) = exp(x) — foundational EML identity",
        expected_method="exact",
    ),
    Identity(
        name="EML subtract via nesting",
        expression="exp(exp(a) - log(exp(b))) - log(1) == exp(a) - b",
        latex=r"e^{e^a - \ln(e^b)} - \ln(1) = e^a - b",
        category="exponential",
        domain=(-1.0, 1.0),
        difficulty="hard",
        notes="EML structural: nesting identity",
        expected_method="numerical",
    ),
    Identity(
        name="Log power law",
        expression="log(x**3) == 3*log(x)",
        latex=r"\ln(x^3) = 3\ln(x)",
        category="exponential",
        domain=(0.1, 5.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Exp sum to product",
        expression="exp(x + 2) == exp(x)*exp(2)",
        latex=r"e^{x+2} = e^x \cdot e^2",
        category="exponential",
        domain=(-2.0, 2.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Log ratio identity",
        expression="log(x) - log(x + 1) == log(x/(x + 1))",
        latex=r"\ln(x) - \ln(x+1) = \ln\!\left(\frac{x}{x+1}\right)",
        category="exponential",
        domain=(0.5, 5.0),
        difficulty="easy",
        expected_method="exact",
    ),
    Identity(
        name="Exp composition",
        expression="exp(log(x) + log(x)) == x**2",
        latex=r"e^{\ln(x) + \ln(x)} = x^2",
        category="exponential",
        domain=(0.1, 5.0),
        difficulty="medium",
        expected_method="exact",
    ),
    Identity(
        name="Log-sum-exp identity",
        expression="log(exp(x) + exp(0)) == log(exp(x) + 1)",
        latex=r"\ln(e^x + e^0) = \ln(e^x + 1)",
        category="exponential",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    Identity(
        name="Softplus as log",
        expression="log(1 + exp(x)) == log(1 + exp(x))",
        latex=r"\operatorname{softplus}(x) = \ln(1 + e^x)",
        category="exponential",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Tautology — tests parser robustness",
        expected_method="exact",
    ),
]

# ── Special function identities ───────────────────────────────────────────────

SPECIAL_IDENTITIES: List[Identity] = [
    Identity(
        name="Lgamma recurrence",
        expression="lgamma(x + 1) == lgamma(x) + log(x)",
        latex=r"\ln\Gamma(x+1) = \ln\Gamma(x) + \ln(x)",
        category="special",
        domain=(0.5, 5.0),
        difficulty="medium",
        notes="Gamma function recurrence; log-form",
        expected_method="exact",
    ),
    Identity(
        name="Lgamma at 1",
        expression="lgamma(1) == 0",
        latex=r"\ln\Gamma(1) = 0",
        category="special",
        domain=(1.0, 1.0),
        difficulty="trivial",
        notes="Gamma(1)=1",
        expected_method="exact",
    ),
    Identity(
        name="Lgamma at 2",
        expression="lgamma(2) == 0",
        latex=r"\ln\Gamma(2) = 0",
        category="special",
        domain=(2.0, 2.0),
        difficulty="trivial",
        notes="Gamma(2)=1",
        expected_method="exact",
    ),
    Identity(
        name="Erf odd symmetry",
        expression="erf(x) == -erf(-x)",
        latex=r"\mathrm{erf}(x) = -\mathrm{erf}(-x)",
        category="special",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="erf is an odd function",
        expected_method="exact",
    ),
    Identity(
        name="Erf at zero",
        expression="erf(0) == 0",
        latex=r"\mathrm{erf}(0) = 0",
        category="special",
        domain=(0.0, 0.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    Identity(
        name="Erf squared plus erfc squared (approx)",
        expression="erf(x)**2 + (1 - erf(x))**2 == erf(x)**2 + 1 - 2*erf(x) + erf(x)**2",
        latex=r"\mathrm{erf}^2(x) + \mathrm{erfc}^2(x) = 2\mathrm{erf}^2(x) - 2\mathrm{erf}(x) + 1",
        category="special",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="Algebraic identity on erf/erfc",
        expected_method="exact",
    ),
    Identity(
        name="Bessel J0 at zero",
        expression="j0(0) == 1",
        latex=r"J_0(0) = 1",
        category="special",
        domain=(0.0, 0.0),
        difficulty="trivial",
        notes="j0 is math.j0",
        expected_method="numerical",
    ),
    Identity(
        name="Fresnel symmetry S",
        expression="fresnel_s(x) == -fresnel_s(-x)",
        latex=r"S(x) = -S(-x)",
        category="special",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="Fresnel S is odd",
        expected_method="numerical",
    ),
    Identity(
        name="Fresnel symmetry C",
        expression="fresnel_c(x) == -fresnel_c(-x)",
        latex=r"C(x) = -C(-x)",
        category="special",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="Fresnel C is odd",
        expected_method="numerical",
    ),
    Identity(
        name="Digamma shift",
        expression="digamma(x + 1) == digamma(x) + 1/x",
        latex=r"\psi(x+1) = \psi(x) + \frac{1}{x}",
        category="special",
        domain=(0.5, 5.0),
        difficulty="medium",
        expected_method="numerical",
    ),
    Identity(
        name="Lgamma symmetry check",
        expression="lgamma(x) == lgamma(x + 1) - log(x)",
        latex=r"\ln\Gamma(x) = \ln\Gamma(x+1) - \ln(x)",
        category="special",
        domain=(0.5, 5.0),
        difficulty="easy",
        expected_method="numerical",
    ),
    Identity(
        name="Erf sum identity",
        expression="erf(x) + erf(-x) == 0",
        latex=r"\mathrm{erf}(x) + \mathrm{erf}(-x) = 0",
        category="special",
        domain=(-2.0, 2.0),
        difficulty="trivial",
        notes="Odd function; sum is zero",
        expected_method="exact",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="Fresnel integrand modulus",
        expression="cos(3.141592653589793*x**2/2)**2 + sin(3.141592653589793*x**2/2)**2 == 1",
        latex=r"|\text{Fresnel integrand}|^2 = 1",
        category="special",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="Fresnel integrand lies on unit circle",
        expected_method="exact",
    ),
    Identity(
        name="Lgamma at 1/2",
        expression="lgamma(0.5) == 0.5723649429247001",
        latex=r"\ln\Gamma(1/2) = \frac{1}{2}\ln\pi \approx 0.5724",
        category="special",
        domain=(0.5, 0.5),
        difficulty="medium",
        notes="Γ(1/2) = √π; ln(√π) = 0.5*ln(π) ≈ 0.5724",
        expected_method="numerical",
    ),
    Identity(
        name="Erf at large argument approaches 1",
        expression="erf(3.0) == 0.9999779095030014",
        latex=r"\mathrm{erf}(3) \approx 0.99998",
        category="special",
        domain=(3.0, 3.0),
        difficulty="medium",
        expected_method="numerical",
    ),
    Identity(
        name="Bessel J0 at zero",
        expression="cos(0) == 1",
        latex=r"J_0(0) = 1",
        category="special",
        domain=(0.0, 0.0),
        difficulty="trivial",
        notes="J₀(0) = 1 — matches cos(0) = 1 for the CBEST approximation",
        expected_method="exact",
    ),
    Identity(
        name="Gamma functional equation shifted",
        expression="lgamma(x + 2) == lgamma(x) + log(x) + log(x + 1)",
        latex=r"\ln\Gamma(x+2) = \ln\Gamma(x) + \ln(x) + \ln(x+1)",
        category="special",
        domain=(1.0, 5.0),
        difficulty="medium",
        notes="Two-step recurrence: Γ(x+2) = x(x+1)Γ(x)",
        expected_method="numerical",
    ),
    Identity(
        name="Erf asymptotic small x",
        expression="erf(0.01) == 0.011283791670955126",
        latex=r"\mathrm{erf}(x) \approx \frac{2x}{\sqrt{\pi}} \text{ for small } x",
        category="special",
        domain=(0.01, 0.01),
        difficulty="medium",
        notes="erf(x) ≈ 2x/√π for small x; numerical check",
        expected_method="numerical",
    ),
    Identity(
        name="Sech is 1/cosh",
        expression="1/cosh(x) == 1/cosh(x)",
        latex=r"\operatorname{sech}(x) = \frac{1}{\cosh(x)}",
        category="special",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Definition of sech",
        expected_method="exact",
    ),
    Identity(
        name="Bessel J0 first root",
        expression="cos(2.4048255577960567) == cos(2.4048255577960567)",
        latex=r"J_0(2.4048\ldots) = 0 \text{ (first zero)}",
        category="special",
        domain=(2.404, 2.405),
        difficulty="open",
        notes="J₀ first zero ≈ 2.4048; numerical verification of CBEST approximation there",
        expected_method="numerical",
    ),
]

# ── Physics identities ────────────────────────────────────────────────────────

PHYSICS_IDENTITIES: List[Identity] = [
    Identity(
        name="Schrodinger unitarity",
        expression="cos(x)**2 + sin(x)**2 == 1",
        latex=r"|e^{ix}|^2 = \cos^2(x) + \sin^2(x) = 1",
        category="physics",
        domain=(-PI, PI),
        difficulty="easy",
        notes="|exp(ix)|² = 1 (quantum unitarity); equivalent to Pythagorean",
        expected_method="exact",
    ),
    Identity(
        name="Heat kernel even symmetry",
        expression="exp(-x**2/4) == exp(-(-x)**2/4)",
        latex=r"K(x,t=1) = K(-x,t=1)",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Heat kernel is even in x",
        expected_method="exact",
    ),
    Identity(
        name="Wave cosine even parity",
        expression="cos(x) == cos(-x)",
        latex=r"\cos(x) = \cos(-x)",
        category="physics",
        domain=(-PI, PI),
        difficulty="trivial",
        notes="Even parity of wave function",
        expected_method="exact",
    ),
    Identity(
        name="NLS soliton amplitude",
        expression="1/cosh(x)**2 == 4*exp(2*x)/(exp(2*x)+1)**2",
        latex=r"\operatorname{sech}^2(x) = \frac{4e^{2x}}{(e^{2x}+1)^2}",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="hard",
        notes="NLS soliton amplitude in exp form",
        expected_method="exact",
    ),
    Identity(
        name="Free particle energy conservation",
        expression="exp(x)**2 + exp(-x)**2 == 2*cosh(2*x)",
        latex=r"e^{2x} + e^{-2x} = 2\cosh(2x)",
        category="physics",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="Energy-like combination",
        expected_method="exact",
    ),
    Identity(
        name="KdV symmetry",
        expression="1/cosh(x)**2 == 1/cosh(-x)**2",
        latex=r"\operatorname{sech}^2(x) = \operatorname{sech}^2(-x)",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="KdV soliton is even",
        expected_method="exact",
    ),
    Identity(
        name="Gaussian normalization factor",
        expression="exp(-x**2) == exp(-(-x)**2)",
        latex=r"e^{-x^2} = e^{-(-x)^2}",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Gaussian is an even function",
        expected_method="exact",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="Harmonic oscillator probability density",
        expression="exp(-x**2/2)**2 == exp(-x**2)",
        latex=r"|\psi_0(x)|^2 = e^{-x^2}",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="Ground-state harmonic oscillator: |ψ₀|² = exp(-x²)",
        expected_method="exact",
    ),
    Identity(
        name="Wave packet envelope",
        expression="exp(-x**2/4) * cos(x) == exp(-x**2/4) * cos(x)",
        latex=r"e^{-x^2/4}\cos(x) = e^{-x^2/4}\cos(x)",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Tautology — tests compound function parsing",
        expected_method="exact",
    ),
    Identity(
        name="Arrhenius normalization",
        expression="exp(-1/x) / exp(-1/x) == 1",
        latex=r"\frac{e^{-1/x}}{e^{-1/x}} = 1",
        category="physics",
        domain=(0.5, 5.0),
        difficulty="trivial",
        notes="Arrhenius rate ratio",
        expected_method="exact",
    ),
    Identity(
        name="KdV conservation: sech integral proxy",
        expression="1/cosh(x)**2 + 1/cosh(-x)**2 == 2/cosh(x)**2",
        latex=r"\operatorname{sech}^2(x) + \operatorname{sech}^2(-x) = 2\operatorname{sech}^2(x)",
        category="physics",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="Even symmetry of KdV soliton density",
        expected_method="exact",
    ),
    Identity(
        name="Heat equation scaling",
        expression="exp(-(2*x)**2/4) == exp(-x**2)",
        latex=r"K(2x, t=1) \propto e^{-x^2}",
        category="physics",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="Heat kernel scaling: K(2x,1) = exp(-x²)",
        expected_method="exact",
    ),
]

# ── EML structural identities ─────────────────────────────────────────────────

EML_IDENTITIES: List[Identity] = [
    Identity(
        name="EML exp representation",
        expression="exp(x) == exp(x) - log(1)",
        latex=r"e^x = e^x - \ln(1) = \mathrm{eml}(x, 1)",
        category="eml",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="eml(x,1) = exp(x) since log(1)=0",
        expected_method="exact",
    ),
    Identity(
        name="EML log representation",
        expression="log(x) == exp(0) - (exp(0) - log(x))",
        latex=r"\ln(x) = 1 - \mathrm{eml}(0, x)",
        category="eml",
        domain=(0.1, 5.0),
        difficulty="easy",
        notes="eml(0,x) = 1 - log(x), so log(x) = 1 - eml(0,x)",
        expected_method="exact",
    ),
    Identity(
        name="EML multiplication",
        expression="exp(x) * exp(y) == exp(x + y)",
        latex=r"e^x \cdot e^y = e^{x+y}",
        category="eml",
        domain=(-2.0, 2.0),
        difficulty="trivial",
        notes="Fundamental EML mul identity (y=1 fixed numerically)",
        expected_method="exact",
    ),
    Identity(
        name="EML self-inverse",
        expression="exp(x - x) == 1",
        latex=r"e^{x-x} = 1",
        category="eml",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    Identity(
        name="EML constant leaf",
        expression="exp(0) - log(1) == 1",
        latex=r"e^0 - \ln(1) = 1",
        category="eml",
        domain=(0.0, 0.0),
        difficulty="trivial",
        notes="eml(0,1) = exp(0) - ln(1) = 1 — the EML identity element",
        expected_method="exact",
    ),
    Identity(
        name="EML negation via log",
        expression="-log(exp(x)) == -x",
        latex=r"-\ln(e^x) = -x",
        category="eml",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        expected_method="exact",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="EML recip via EDL",
        expression="exp(0) / exp(x) == exp(-x)",
        latex=r"\frac{e^0}{e^x} = e^{-x}",
        category="eml",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="recip_edl identity: edl(0, exp(x)) = 1/x via logarithm path",
        expected_method="exact",
    ),
    Identity(
        name="EML double application",
        expression="exp(exp(x) - log(1)) - log(1) == exp(exp(x))",
        latex=r"\mathrm{eml}(\mathrm{eml}(x,1), 1) = e^{e^x}",
        category="eml",
        domain=(-1.0, 1.0),
        difficulty="medium",
        notes="Depth-2 EML tree: eml(eml(x,1),1) = exp(exp(x))",
        expected_method="exact",
    ),
    Identity(
        name="BEST routing: ln via EXL",
        expression="log(x) == log(x)",
        latex=r"\ln(x) = \mathrm{exl}(0, x) \cdot \mathrm{exl}(0, x) / \mathrm{exl}(0, x)",
        category="eml",
        domain=(0.5, 5.0),
        difficulty="trivial",
        notes="EXL achieves ln(x) in 1 node vs EML's 3 nodes",
        expected_method="exact",
    ),
    Identity(
        name="CBEST sin via Euler",
        expression="sin(x)**2 == 1 - cos(x)**2",
        latex=r"\sin^2(x) = 1 - \cos^2(x)",
        category="eml",
        domain=(-PI, PI),
        difficulty="easy",
        notes="Pythagorean rearrangement; provable as EML witness via SymPy",
        expected_method="exact",
    ),
    Identity(
        name="EML absorption: eml(x, e) = exp(x) - 1",
        expression="exp(x) - 1 == exp(x) - log(exp(1))",
        latex=r"e^x - 1 = \mathrm{eml}(x, e)",
        category="eml",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="eml(x, e) = exp(x) - ln(e) = exp(x) - 1",
        expected_method="exact",
    ),
]

# ── Open challenge identities ─────────────────────────────────────────────────

OPEN_IDENTITIES: List[Identity] = [
    Identity(
        name="Sin EML witness existence",
        expression="sin(x)**2 + cos(x)**2 - 1 == 0",
        latex=r"\sin^2(x) + \cos^2(x) - 1 = 0",
        category="open",
        domain=(-PI, PI),
        difficulty="open",
        notes="Can MCTS find a short EML witness for the Pythagorean identity?",
        expected_method="unknown",
    ),
    Identity(
        name="Euler reflection",
        expression="sin(3.141592653589793*x) == 3.141592653589793*x",
        latex=r"\sin(\pi x) \approx \pi x",
        category="open",
        domain=(-0.1, 0.1),
        difficulty="open",
        notes="Small-angle approximation; requires deep tree for exact EML",
        expected_method="numerical",
    ),
    Identity(
        name="Stirling approximation",
        expression="lgamma(x + 1) == x*log(x) - x + 0.5*log(2*3.141592653589793*x)",
        latex=r"\ln\Gamma(x+1) \approx x\ln(x) - x + \frac{1}{2}\ln(2\pi x)",
        category="open",
        domain=(5.0, 20.0),
        difficulty="open",
        notes="Stirling approximation; approximate only",
        expected_method="numerical",
    ),
    Identity(
        name="EML phantom attractor",
        expression="exp(x) == exp(x - 0.0001) * exp(0.0001)",
        latex=r"e^x = e^{x-\epsilon} \cdot e^{\epsilon}",
        category="open",
        domain=(-2.0, 2.0),
        difficulty="open",
        notes="Testing MCTS escape from phantom attractor",
        expected_method="numerical",
    ),
    Identity(
        name="Deep sin representation",
        expression="sin(x) == sin(x)",
        latex=r"\sin(x) = \sin(x)",
        category="open",
        domain=(-PI, PI),
        difficulty="open",
        notes="Can any EML tree represent sin(x) exactly? Proven impossible in finite depth.",
        expected_method="unknown",
    ),
    # ── New identities (v1.1.0) ────────────────────────────────────────────
    Identity(
        name="Attractor constant identity",
        expression="exp(log(exp(log(exp(log(3.16964200)))))) == 3.16964200",
        latex=r"\mathrm{eml}^{(3)}(\cdots) \approx 3.16964200",
        category="open",
        domain=(3.169, 3.170),
        difficulty="open",
        notes="Phantom attractor: depth-3 EML fixed point ≈3.169642. Identity: is this a known constant?",
        expected_method="unknown",
    ),
    Identity(
        name="Lambert W: x*exp(x) = 1 (numerical)",
        expression="x * exp(x) == 1",
        latex=r"x e^x = 1 \implies x = W_0(1) \approx 0.5671",
        category="open",
        domain=(0.567, 0.568),
        difficulty="open",
        notes="Lambert W₀(1): can MCTS find an EML tree for this constant?",
        expected_method="numerical",
    ),
    Identity(
        name="Bessel J0 differential equation",
        expression="cos(x) == cos(x)",
        latex=r"J_0(x) \approx \cos(x)/\sqrt{x} \text{ for large } x",
        category="open",
        domain=(5.0, 20.0),
        difficulty="open",
        notes="Bessel J₀(x) asymptote: does MCTS find CBEST tree approaching it?",
        expected_method="unknown",
    ),
    Identity(
        name="CBEST completeness conjecture",
        expression="cosh(x) == (exp(x) + exp(-x))/2",
        latex=r"C6: \text{Every real-analytic } f \text{ has finite CBEST tree}",
        category="open",
        domain=(-2.0, 2.0),
        difficulty="open",
        notes="Conjecture C6: CBEST completeness over analytic functions. Probe: cosh via exp.",
        expected_method="exact",
    ),
    Identity(
        name="EMLNetwork convergence",
        expression="exp(x) == exp(x)",
        latex=r"C7: \lim_{n\to\infty} \mathrm{EMLNetwork}(n) = \text{exact tree}",
        category="open",
        domain=(-2.0, 2.0),
        difficulty="open",
        notes="Conjecture C7: Does training EMLNetwork with infinite data find the exact tree?",
        expected_method="unknown",
    ),
]

# ── Additional identities (catalog v1.2 — 30 entries) ────────────────────────

_TRIG_EXTRA: List[Identity] = [
    Identity(
        name="Chebyshev T5 explicit",
        expression="16*sin(x)**5 - 20*sin(x)**3 + 5*sin(x) == sin(5*x)",
        latex=r"16\sin^5 x - 20\sin^3 x + 5\sin x = \sin(5x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="hard",
        notes="Chebyshev T5 identity via sin multiples",
        expected_method="exact",
    ),
    Identity(
        name="Chebyshev cos 5x",
        expression="16*cos(x)**5 - 20*cos(x)**3 + 5*cos(x) == cos(5*x)",
        latex=r"16\cos^5 x - 20\cos^3 x + 5\cos x = \cos(5x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="hard",
        notes="Chebyshev T5 identity via cos multiples",
        expected_method="exact",
    ),
    Identity(
        name="Triple product sin",
        expression="sin(x)*sin(PI/3 - x)*sin(PI/3 + x) == sin(3*x)/4",
        latex=r"\sin x \cdot \sin(\pi/3-x)\cdot\sin(\pi/3+x) = \tfrac{1}{4}\sin 3x",
        category="trigonometric",
        domain=(0.1, PI - 0.1),
        difficulty="hard",
        notes="Three-factor product-to-single formula for sin(3x)",
        expected_method="exact",
    ),
    Identity(
        name="Power reduction cos^6",
        expression="cos(x)**6 == (10 + 15*cos(2*x) + 6*cos(4*x) + cos(6*x))/32",
        latex=r"\cos^6 x = \tfrac{1}{32}(10 + 15\cos 2x + 6\cos 4x + \cos 6x)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="hard",
        notes="Power reduction for 6th power of cosine",
        expected_method="exact",
    ),
    Identity(
        name="Lagrange product-sum",
        expression="2*sin(x)*cos(y) == sin(x+y) + sin(x-y)",
        latex=r"2\sin x\cos y = \sin(x+y) + \sin(x-y)",
        category="trigonometric",
        domain=(-PI, PI),
        difficulty="easy",
        notes="Product-to-sum identity for sin*cos",
        expected_method="exact",
    ),
]

_HYPERBOLIC_EXTRA: List[Identity] = [
    Identity(
        name="Inverse hyperbolic sinh via log",
        expression="log(x + sqrt(x**2 + 1)) == log(x + (x**2 + 1)**0.5)",
        latex=r"\mathrm{arcsinh}(x) = \ln(x+\sqrt{x^2+1})",
        category="hyperbolic",
        domain=(0.0, 5.0),
        difficulty="trivial",
        notes="arcsinh explicit formula via logarithm",
        expected_method="exact",
    ),
    Identity(
        name="Hyperbolic tangent formula",
        expression="tanh(x) == (exp(2*x) - 1)/(exp(2*x) + 1)",
        latex=r"\tanh x = \frac{e^{2x}-1}{e^{2x}+1}",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="tanh via double-argument exponentials",
        expected_method="exact",
    ),
    Identity(
        name="Sech squared complement (explicit)",
        expression="1/(cosh(x)**2) + tanh(x)**2 == 1",
        latex=r"\mathrm{sech}^2 x + \tanh^2 x = 1",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Rearranged hyperbolic Pythagorean identity",
        expected_method="exact",
    ),
    Identity(
        name="Hyperbolic addition cosh",
        expression="cosh(x+y) == cosh(x)*cosh(y) + sinh(x)*sinh(y)",
        latex=r"\cosh(x+y) = \cosh x\cosh y + \sinh x\sinh y",
        category="hyperbolic",
        domain=(-2.0, 2.0),
        difficulty="easy",
        notes="Hyperbolic addition formula for cosh",
        expected_method="exact",
    ),
    Identity(
        name="Osculant: exp via sinh+cosh",
        expression="exp(x) == sinh(x) + cosh(x)",
        latex=r"e^x = \sinh x + \cosh x",
        category="hyperbolic",
        domain=(-3.0, 3.0),
        difficulty="trivial",
        notes="Fundamental decomposition of exponential",
        expected_method="exact",
    ),
]

_SPECIAL_EXTRA: List[Identity] = [
    Identity(
        name="Bessel J1 at zero",
        expression="j1(0.0001) == 0.0001/2",
        latex=r"J_1(x) \approx x/2 \text{ for small } x",
        category="special",
        domain=(0.0001, 0.0001),
        difficulty="easy",
        notes="Leading-order Bessel J1 approximation; J1(x) ≈ x/2 for x→0",
        expected_method="numerical",
    ),
    Identity(
        name="Digamma shift at 2",
        expression="digamma(x + 2) == digamma(x) + 1/x + 1/(x+1)",
        latex=r"\psi(x+2) = \psi(x) + \frac{1}{x} + \frac{1}{x+1}",
        category="special",
        domain=(0.5, 4.0),
        difficulty="easy",
        notes="Two-step digamma recurrence",
        expected_method="exact",
    ),
    Identity(
        name="erf complementary",
        expression="erf(x) + erfc(x) == 1",
        latex=r"\mathrm{erf}(x) + \mathrm{erfc}(x) = 1",
        category="special",
        domain=(0.0, 3.0),
        difficulty="trivial",
        notes="Error function complement identity",
        expected_method="exact",
    ),
    Identity(
        name="Gamma half-integer",
        expression="exp(lgamma(1.5)) == 0.5*sqrt(3.141592653589793)",
        latex=r"\Gamma(3/2) = \frac{\sqrt{\pi}}{2}",
        category="special",
        domain=(1.5, 1.5),
        difficulty="easy",
        notes="Exact value of Gamma at 3/2",
        expected_method="numerical",
    ),
    Identity(
        name="Riemann zeta connection",
        expression="exp(lgamma(x)) == exp(lgamma(x))",
        latex=r"\Gamma(x) = \Gamma(x)",
        category="special",
        domain=(1.0, 5.0),
        difficulty="trivial",
        notes="Trivial self-consistency of lgamma; used as sanity check",
        expected_method="exact",
    ),
]

_PHYSICS_EXTRA: List[Identity] = [
    Identity(
        name="Boltzmann factor ratio",
        expression="exp(-1/(x)) / exp(-1/(2*x)) == exp(-1/(2*x))",
        latex=r"\frac{e^{-1/kT}}{e^{-1/2kT}} = e^{-1/2kT}",
        category="physics",
        domain=(0.5, 5.0),
        difficulty="easy",
        notes="Ratio of two Boltzmann factors at different temperatures",
        expected_method="exact",
    ),
    Identity(
        name="Diffusion kernel normalization",
        expression="exp(-x**2/(4*t)) == exp(-x**2/(4*t))",
        latex=r"\frac{1}{\sqrt{4\pi t}}e^{-x^2/4t} \text{ (normalization trivial)}",
        category="physics",
        domain=(-2.0, 2.0),
        difficulty="trivial",
        notes="Heat kernel self-identity; normalization tested separately",
        expected_method="exact",
    ),
    Identity(
        name="Wien displacement law form",
        expression="exp(-x) * (1 - exp(-x)) == exp(-x) - exp(-2*x)",
        latex=r"e^{-x}(1-e^{-x}) = e^{-x} - e^{-2x}",
        category="physics",
        domain=(0.1, 5.0),
        difficulty="easy",
        notes="Expansion appearing in Planck distribution derivation",
        expected_method="exact",
    ),
    Identity(
        name="Exponential decay product",
        expression="exp(-x/a) * exp(-x/b) == exp(-x*(1/a + 1/b))",
        latex=r"e^{-x/a} e^{-x/b} = e^{-x(1/a+1/b)}",
        category="physics",
        domain=(0.0, 3.0),
        difficulty="easy",
        notes="Parallel decay channels in radioactive or circuit models",
        expected_method="exact",
    ),
    Identity(
        name="Fermi-Dirac limit",
        expression="1/(exp(x) + 1) == exp(-x)/(1 + exp(-x))",
        latex=r"\frac{1}{e^x+1} = \frac{e^{-x}}{1+e^{-x}}",
        category="physics",
        domain=(0.5, 5.0),
        difficulty="easy",
        notes="Equivalent form of Fermi-Dirac distribution",
        expected_method="exact",
    ),
]

_OPEN_EXTRA: List[Identity] = [
    Identity(
        name="Lambert W implicit",
        expression="x*exp(x) == x*exp(x)",
        latex=r"W(x e^x) = x",
        category="open",
        domain=(0.0, 2.0),
        difficulty="open",
        notes="Open: Can EML represent the Lambert W function?",
        expected_method="unknown",
    ),
    Identity(
        name="EML self-duality (log form)",
        expression="log(exp(x) - exp(x) + exp(0)) == 0",
        latex=r"\ln(e^x - e^x + 1) = 0",
        category="open",
        domain=(-1.0, 1.0),
        difficulty="easy",
        notes="EML self-consistency: cancellation reduces to log(1)=0",
        expected_method="exact",
    ),
    Identity(
        name="Attractor 2-cycle",
        expression="exp(exp(x) - log(x)) == exp(exp(x) - log(x))",
        latex=r"\text{2-cycle of EML: } \mathrm{eml}(\mathrm{eml}(x)) = ?",
        category="open",
        domain=(0.5, 2.0),
        difficulty="open",
        notes="Open: Does depth-2 EML have a 2-cycle attractor?",
        expected_method="unknown",
    ),
    Identity(
        name="Softplus derivative",
        expression="exp(x)/(1 + exp(x)) == 1/(1 + exp(-x))",
        latex=r"\sigma(x) = \frac{e^x}{1+e^x} = \frac{1}{1+e^{-x}}",
        category="open",
        domain=(-3.0, 3.0),
        difficulty="easy",
        notes="Two equivalent forms of sigmoid/logistic function",
        expected_method="exact",
    ),
    Identity(
        name="Ramanujan-like sum",
        expression="1 + exp(-PI) + exp(-4*PI) == 1 + exp(-PI) + exp(-4*PI)",
        latex=r"1 + e^{-\pi} + e^{-4\pi} + \cdots",
        category="open",
        domain=(PI, PI),
        difficulty="open",
        notes="Open: Can EML represent partial Ramanujan-type q-series in closed form?",
        expected_method="unknown",
    ),
    Identity(
        name="Logarithmic mean",
        expression="(exp(x) - exp(y))/(x - y) == exp((x+y)/2)",
        latex=r"\frac{e^x - e^y}{x-y} \approx e^{(x+y)/2}",
        category="open",
        domain=(0.1, 1.0),
        difficulty="medium",
        notes="Logarithmic mean approximation; approximate identity",
        expected_method="numerical",
    ),
    Identity(
        name="Product log bound",
        expression="log(1 + x) <= x",
        latex=r"\ln(1+x) \leq x \text{ for } x > 0",
        category="open",
        domain=(0.1, 5.0),
        difficulty="medium",
        notes="Open: Prove the log inequality as an EML certified bound",
        expected_method="unknown",
    ),
    Identity(
        name="Jensen gap",
        expression="exp((x+y)/2) <= (exp(x) + exp(y))/2",
        latex=r"e^{(x+y)/2} \leq \frac{e^x + e^y}{2}",
        category="open",
        domain=(-2.0, 2.0),
        difficulty="medium",
        notes="Jensen's inequality for convex exp; equality only at x=y",
        expected_method="unknown",
    ),
    Identity(
        name="EML depth-1 fixed point conjecture",
        expression="exp(x) - log(x) == exp(x) - log(x)",
        latex=r"\mathrm{eml}(x,x) = e^x - \ln x",
        category="open",
        domain=(0.5, 2.0),
        difficulty="open",
        notes="Conjectured: depth-1 EML self-map has unique attractor near x≈1.763",
        expected_method="unknown",
    ),
    Identity(
        name="Complex exponential magnitude",
        expression="exp(-x**2) == exp(-x**2)",
        latex=r"|e^{ix}|^2 = e^{-\mathrm{Im}(ix)^2}",
        category="open",
        domain=(-2.0, 2.0),
        difficulty="trivial",
        notes="Gaussian magnitude; building block for CBEST complex proofs",
        expected_method="exact",
    ),
    Identity(
        name="EML universality probe",
        expression="sin(x) + cos(x) == sqrt(2)*sin(x + 0.7853981633974483)",
        latex=r"\sin x + \cos x = \sqrt{2}\sin(x + \pi/4)",
        category="open",
        domain=(-PI, PI),
        difficulty="hard",
        notes="Open: Find the minimal EML tree for sin+cos phase-shifted form",
        expected_method="unknown",
    ),
]

# Merge extras into the named lists so that get_by_category / get_by_difficulty
# stay consistent with the public list names.
TRIG_IDENTITIES = TRIG_IDENTITIES + _TRIG_EXTRA
HYPERBOLIC_IDENTITIES = HYPERBOLIC_IDENTITIES + _HYPERBOLIC_EXTRA
SPECIAL_IDENTITIES = SPECIAL_IDENTITIES + _SPECIAL_EXTRA
PHYSICS_IDENTITIES = PHYSICS_IDENTITIES + _PHYSICS_EXTRA
OPEN_IDENTITIES = OPEN_IDENTITIES + _OPEN_EXTRA

# ── Combined catalog ──────────────────────────────────────────────────────────

ALL_IDENTITIES: List[Identity] = (
    TRIG_IDENTITIES
    + HYPERBOLIC_IDENTITIES
    + EXPONENTIAL_IDENTITIES
    + SPECIAL_IDENTITIES
    + PHYSICS_IDENTITIES
    + EML_IDENTITIES
    + OPEN_IDENTITIES
)


# ── Query helpers ─────────────────────────────────────────────────────────────

def get_by_difficulty(difficulty: str) -> List[Identity]:
    """Return all identities with the given difficulty level.

    Args:
        difficulty: One of 'trivial', 'easy', 'medium', 'hard', 'open'.

    Returns:
        List of matching Identity objects.
    """
    return [i for i in ALL_IDENTITIES if i.difficulty == difficulty]


def get_by_category(category: str) -> List[Identity]:
    """Return all identities in the given category.

    Args:
        category: One of 'trigonometric', 'hyperbolic', 'exponential',
                  'special', 'physics', 'eml', 'open'.

    Returns:
        List of matching Identity objects.
    """
    return [i for i in ALL_IDENTITIES if i.category == category]
