"""Fixture-backed preview compiler surface for FEF-P2.

This module intentionally supports one selected fixture. It is a clean-room
quickstart scaffold, not a general Forge/eFrog compiler.
"""

from __future__ import annotations

import importlib.util
import json
import math
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


SCHEMA_VERSION = "monogate.forge_preview_packet.v0"
SUPPORTED_TARGETS = ("python", "javascript")
SAMPLES = (-2.0, -1.0, 0.0, 0.75, 1.5, 2.0)

CLAIM_FLAGS = {
    "package_published": False,
    "public_ready": False,
    "compiler_correctness_claim": False,
    "formal_equivalence_claim": False,
    "runtime_performance_claim": False,
    "production_toolchain_claim": False,
    "verilog_claim": False,
    "lean_proof_claim": False,
    "zkproof_claim": False,
    "silicon_claim": False,
    "checkout_enabled": False,
}


@dataclass(frozen=True)
class CheckFrame:
    x: float
    source: float
    python: float
    javascript: float

    @property
    def max_abs_error(self) -> float:
        return max(abs(self.source - self.python), abs(self.source - self.javascript))


def capabilities() -> dict:
    return {
        "schemaVersion": "monogate.forge_preview_capabilities.v0",
        "package": "monogate-forge-preview",
        "distributionStatus": "local_scaffold_not_published",
        "supportedFixtures": ["gaussian.py"],
        "supportedTargets": list(SUPPORTED_TARGETS),
        "blockedTargets": ["verilog", "lean", "zkproof", "all"],
        "claimFlags": dict(CLAIM_FLAGS),
    }


def load_source_function(source: Path) -> Callable[[float], float]:
    source = source.resolve()
    spec = importlib.util.spec_from_file_location("fef_p2_source_fixture", source)
    if spec is None or spec.loader is None:
        raise ValueError(f"cannot load source fixture: {source}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    fn = getattr(module, "gaussian", None)
    if not callable(fn):
        raise ValueError("only selected gaussian.py fixture is supported")
    return fn


def emit_source(target: str) -> str:
    if target == "python":
        return (
            "\"\"\"Generated by monogate-forge-preview local scaffold.\"\"\"\n\n"
            "import math\n\n\n"
            "def gaussian(x: float) -> float:\n"
            "    return math.exp(-0.5 * x * x)\n"
        )
    if target == "javascript":
        return (
            "// Generated by monogate-forge-preview local scaffold.\n\n"
            "export function gaussian(x) {\n"
            "  return Math.exp(-0.5 * x * x);\n"
            "}\n"
        )
    raise ValueError(f"unsupported preview target: {target}")


def emit(target: str, source: Path, out: Path) -> Path:
    load_source_function(source)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(emit_source(target), encoding="utf-8")
    return out


def _run_generated_python(path: Path, x: float) -> float:
    spec = importlib.util.spec_from_file_location("fef_p2_generated_python", path)
    if spec is None or spec.loader is None:
        raise ValueError(f"cannot load generated Python target: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return float(module.gaussian(x))


def _run_generated_javascript(path: Path, x: float) -> float:
    script = (
        "const mod = await import(process.argv[2]);\n"
        "const x = Number(process.argv[3]);\n"
        "console.log(mod.gaussian(x).toPrecision(17));\n"
    )
    with tempfile.NamedTemporaryFile("w", suffix=".mjs", delete=False, encoding="utf-8") as handle:
        handle.write(script)
        runner = Path(handle.name)
    try:
        proc = subprocess.run(
            ["node", str(runner), path.resolve().as_uri(), str(x)],
            check=True,
            capture_output=True,
            text=True,
        )
    finally:
        runner.unlink(missing_ok=True)
    return float(proc.stdout.strip())


def check(source: Path, targets: list[str], work_dir: Path) -> dict:
    unknown = sorted(set(targets) - set(SUPPORTED_TARGETS))
    if unknown:
        raise ValueError(f"unsupported preview targets: {', '.join(unknown)}")
    if set(targets) != set(SUPPORTED_TARGETS):
        raise ValueError("FEF-P2 quickstart requires both python and javascript targets")

    source_fn = load_source_function(source)
    generated_dir = work_dir / "generated"
    py_path = emit("python", source, generated_dir / "gaussian.py")
    js_path = emit("javascript", source, generated_dir / "gaussian.mjs")

    frames = [
        CheckFrame(
            x=x,
            source=float(source_fn(x)),
            python=_run_generated_python(py_path, x),
            javascript=_run_generated_javascript(js_path, x),
        )
        for x in SAMPLES
    ]
    max_abs_error = max(frame.max_abs_error for frame in frames)
    return {
        "schemaVersion": "monogate.forge_preview_check.v0",
        "status": "pass" if max_abs_error <= 1e-12 else "fail",
        "source": str(source),
        "targets": list(SUPPORTED_TARGETS),
        "sampleCount": len(frames),
        "maxAbsError": max_abs_error,
        "frames": [
            {
                "x": frame.x,
                "source": frame.source,
                "python": frame.python,
                "javascript": frame.javascript,
                "maxAbsError": frame.max_abs_error,
            }
            for frame in frames
        ],
        "claimFlags": dict(CLAIM_FLAGS),
    }


def packet(source: Path, targets: list[str], work_dir: Path) -> dict:
    result = check(source, targets, work_dir)
    return {
        "schemaVersion": SCHEMA_VERSION,
        "packetId": "fef_p2_gaussian_preview_packet",
        "status": result["status"],
        "source": str(source),
        "targets": result["targets"],
        "sampleCount": result["sampleCount"],
        "maxAbsError": result["maxAbsError"],
        "claimBoundary": "local scaffold preview only; no package publication, compiler correctness, formal equivalence, runtime performance, Verilog, proof, silicon, or checkout claim",
        "claimFlags": dict(CLAIM_FLAGS),
        "check": result,
    }


def write_json(data: dict, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True, allow_nan=False) + "\n", encoding="utf-8")
    return path
