"""
Session 69 — Algorithmic Randomness in EML

Martin-Löf randomness, Chaitin's Omega, normal numbers, and computable reals
classified through the EML depth hierarchy.

Key theorem: A real number is computable iff its digit-expansion function n↦d_n
is EML-finite as a function on ℤ. True randomness = EML-∞.
"""

from __future__ import annotations
import math
import json
from dataclasses import dataclass, field
from typing import Callable, Optional
from fractions import Fraction


# ---------------------------------------------------------------------------
# EML depth constants
# ---------------------------------------------------------------------------
EML_INF = float("inf")


@dataclass
class EMLClass:
    depth: float  # 0, 1, 2, 3, or inf
    label: str
    reason: str

    def __str__(self) -> str:
        d = "∞" if self.depth == EML_INF else str(int(self.depth))
        return f"EML-{d}: {self.label}"


# ---------------------------------------------------------------------------
# Computable reals and their EML classification
# ---------------------------------------------------------------------------

@dataclass
class ComputableReal:
    """A real number defined by a computable digit-expansion function."""
    name: str
    description: str
    eml_class: EMLClass
    generating_formula: str
    digit_fn: Optional[Callable[[int], int]] = field(default=None, repr=False)

    def digits(self, n: int, base: int = 10) -> list[int]:
        """Return first n digits in given base."""
        if self.digit_fn is not None:
            return [self.digit_fn(k) for k in range(n)]
        return []

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "eml_class": str(self.eml_class),
            "eml_depth": self.eml_class.depth if self.eml_class.depth != EML_INF else "inf",
            "generating_formula": self.generating_formula,
        }


def _pi_digit(n: int) -> int:
    """n-th decimal digit of pi (naive, slow — illustrative only)."""
    # Bailey–Borwein–Plouffe for hex digits; here we just use math
    val = math.pi
    s = f"{val:.50f}".replace(".", "")
    return int(s[n]) if n < len(s) else 0


def _e_digit(n: int) -> int:
    val = math.e
    s = f"{val:.50f}".replace(".", "")
    return int(s[n]) if n < len(s) else 0


def _sqrt2_digit(n: int) -> int:
    val = math.sqrt(2)
    s = f"{val:.50f}".replace(".", "")
    return int(s[n]) if n < len(s) else 0


def _champernowne_digit(n: int) -> int:
    """0.123456789101112... concatenation of naturals."""
    s = "".join(str(k) for k in range(1, 1000))
    return int(s[n]) if n < len(s) else 0


# Known computable reals and their EML classification
COMPUTABLE_REALS: list[ComputableReal] = [
    ComputableReal(
        name="π",
        description="Circle constant; computable via BBP formula",
        eml_class=EMLClass(3, "π", "Defined via arctan (EML-3) or sin^{-1}; series converges in EML-3"),
        generating_formula="π = 4·arctan(1) = 4·(1 - 1/3 + 1/5 - ...) [Leibniz]; BBP: π = Σ(1/16^k)(4/(8k+1)-...)",
        digit_fn=_pi_digit,
    ),
    ComputableReal(
        name="e",
        description="Euler's number; computable via exp(1)",
        eml_class=EMLClass(1, "e = exp(1)", "Direct output of EML-1 atom exp at x=1"),
        generating_formula="e = exp(1) = Σ 1/n!",
        digit_fn=_e_digit,
    ),
    ComputableReal(
        name="√2",
        description="Square root of 2; algebraic, computable via Newton's method",
        eml_class=EMLClass(2, "√2 = exp(½·ln 2)", "exp(½·ln(2)) — one exp composed with one ln = EML-2"),
        generating_formula="√2 = exp(ln(2)/2); Newton: x_{n+1} = (x_n + 2/x_n)/2",
        digit_fn=_sqrt2_digit,
    ),
    ComputableReal(
        name="ln 2",
        description="Natural log of 2; EML-2 (output of ln gate)",
        eml_class=EMLClass(2, "ln 2", "Output of the ln gate applied to 2 (EML-0 integer)"),
        generating_formula="ln(2) = 1 - 1/2 + 1/3 - ... [alternating harmonic]",
        digit_fn=None,
    ),
    ComputableReal(
        name="Champernowne C₁₀",
        description="0.123456789101112... — computable, normal, but simple recurrence",
        eml_class=EMLClass(2, "C₁₀", "Generated by n↦digit(n) = rational arithmetic on n → EML-2"),
        generating_formula="C₁₀ = 0.1 2 3 4 5 6 7 8 9 10 11 12 ...",
        digit_fn=_champernowne_digit,
    ),
    ComputableReal(
        name="Liouville constant",
        description="Σ 10^{-n!} — transcendental, computable, not normal",
        eml_class=EMLClass(2, "Σ 10^{-n!}", "Each term is exp(-n!·ln 10) = EML-1; sum is EML-2"),
        generating_formula="L = Σ_{n=1}^∞ 10^{-n!} = 0.110001000000000000000001...",
        digit_fn=None,
    ),
]


# ---------------------------------------------------------------------------
# Martin-Löf Randomness
# ---------------------------------------------------------------------------

@dataclass
class MartinLofRandomness:
    """
    Martin-Löf randomness: a sequence ω is random iff it passes all
    effectively null (measure-zero) tests — equivalently, ω does not belong
    to any computably enumerable set of measure zero.

    EML perspective: a random sequence has no EML-finite generating function;
    its complexity is EML-∞.
    """

    @staticmethod
    def frequency_test(seq: list[int], expected: float = 0.5, tol: float = 0.1) -> dict:
        """Monobit frequency test — first test in NIST SP 800-22."""
        n = len(seq)
        ones = sum(seq)
        freq = ones / n
        passes = abs(freq - expected) < tol
        return {
            "test": "monobit_frequency",
            "n": n,
            "ones": ones,
            "frequency": freq,
            "expected": expected,
            "passes": passes,
        }

    @staticmethod
    def runs_test(seq: list[int]) -> dict:
        """Runs test — counts alternating runs."""
        n = len(seq)
        runs = 1 + sum(1 for i in range(1, n) if seq[i] != seq[i - 1])
        # expected runs ≈ 2n·p·(1-p) where p = freq of 1s
        p = sum(seq) / n
        expected_runs = 2 * n * p * (1 - p)
        ratio = runs / expected_runs if expected_runs > 0 else float("nan")
        return {
            "test": "runs",
            "n": n,
            "observed_runs": runs,
            "expected_runs": round(expected_runs, 2),
            "ratio": round(ratio, 4),
            "passes": 0.8 < ratio < 1.2,
        }

    @staticmethod
    def block_entropy_test(seq: list[int], block_size: int = 8) -> dict:
        """Block entropy test — measure entropy of non-overlapping blocks."""
        n = len(seq)
        blocks = {}
        for i in range(0, n - block_size + 1, block_size):
            b = tuple(seq[i : i + block_size])
            blocks[b] = blocks.get(b, 0) + 1
        total = sum(blocks.values())
        entropy = -sum((c / total) * math.log2(c / total) for c in blocks.values() if c > 0)
        max_entropy = block_size  # bits
        ratio = entropy / max_entropy
        return {
            "test": "block_entropy",
            "block_size": block_size,
            "unique_blocks": len(blocks),
            "entropy_bits": round(entropy, 4),
            "max_entropy_bits": max_entropy,
            "ratio": round(ratio, 4),
            "passes": ratio > 0.9,
        }

    @staticmethod
    def classify_sequence(seq: list[int]) -> EMLClass:
        """
        Classify a binary sequence by its EML depth.
        - If generated by a known EML-finite formula → that depth
        - If passes all randomness tests → EML-∞ (empirically)
        """
        freq = MartinLofRandomness.frequency_test(seq)
        runs = MartinLofRandomness.runs_test(seq)
        blk = MartinLofRandomness.block_entropy_test(seq)
        n_pass = sum([freq["passes"], runs["passes"], blk["passes"]])
        if n_pass == 3:
            return EMLClass(EML_INF, "empirically random", "Passes ML randomness tests → no EML-finite generator")
        return EMLClass(2, "structured", "Fails randomness tests → EML-finite structure detectable")


# ---------------------------------------------------------------------------
# Chaitin's Omega
# ---------------------------------------------------------------------------

@dataclass
class ChaitinOmega:
    """
    Chaitin's Omega Ω = Σ_{p halts} 2^{-|p|}

    Properties:
    - 0 < Ω < 1
    - Ω is left-computable (can approximate from below)
    - Ω is not right-computable (halting problem)
    - Ω is Martin-Löf random
    - EML classification: EML-∞ (no EML-finite expression for its digits)

    We can compute lower bounds Ω_n using all programs of length ≤ n
    that halt within T steps.
    """

    @staticmethod
    def lower_bound(max_prog_len: int = 6, max_steps: int = 100) -> dict:
        """
        Compute a lower bound on Ω by enumerating short programs
        (represented as integers, simulated as counter machines).
        """
        # We model "programs" as integers p and "halting" as p being
        # a sum of distinct powers: if binary(p) has even weight → halts
        # This is a toy model preserving the probabilistic structure.
        total = Fraction(0)
        halting = []
        for p in range(1, 2 ** max_prog_len):
            bits = bin(p).count("1")
            prog_len = p.bit_length()
            # Toy halting criterion: halts iff popcount(p) is even
            if bits % 2 == 0:
                total += Fraction(1, 2 ** prog_len)
                halting.append(p)
        return {
            "max_prog_len": max_prog_len,
            "halting_programs": len(halting),
            "omega_lower_bound": float(total),
            "omega_lower_bound_exact": str(total),
            "eml_class": "EML-∞",
            "reason": "No EML-finite formula for Omega's digits; left-computable but not right-computable",
        }

    @staticmethod
    def eml_classification() -> EMLClass:
        return EMLClass(
            EML_INF,
            "Chaitin Ω",
            "Ω is Martin-Löf random → no EML-finite generating function. "
            "Any truncation Ω_n ≈ EML-2 but the limit is EML-∞.",
        )


# ---------------------------------------------------------------------------
# Normal numbers
# ---------------------------------------------------------------------------

@dataclass
class NormalNumber:
    """
    A number α is normal in base b iff for every finite string s of length k,
    the frequency of s in the base-b expansion of α approaches b^{-k}.

    EML classification:
    - Normal numbers: EML-∞ (frequency function has dense zeros)
    - Borel's theorem: almost all reals are normal → EML-∞ a.e.
    - Computable normal numbers exist (Champernowne, Copeland-Erdős)
      but their digit functions are EML-2
    """

    name: str
    base: int
    is_normal: bool
    is_computable: bool
    eml_depth: float
    construction: str

    def eml_class(self) -> EMLClass:
        if self.eml_depth == EML_INF:
            return EMLClass(EML_INF, self.name, "Infinite zeros in frequency deviation function → EML-∞")
        return EMLClass(self.eml_depth, self.name, "Computable normal number via explicit construction")

    def frequency_deviation(self, digits: list[int], digit: int) -> list[float]:
        """
        Compute running frequency deviation of `digit` from expected 1/base.
        Returns list of deviations — for a truly normal number this oscillates
        infinitely → EML-∞ behavior.
        """
        expected = 1.0 / self.base
        deviations = []
        count = 0
        for i, d in enumerate(digits):
            if d == digit:
                count += 1
            freq = count / (i + 1)
            deviations.append(freq - expected)
        return deviations

    def zero_crossings(self, digits: list[int], digit: int) -> int:
        """Count zero crossings of frequency deviation — proxy for EML-∞."""
        devs = self.frequency_deviation(digits, digit)
        crossings = sum(1 for i in range(1, len(devs)) if devs[i - 1] * devs[i] < 0)
        return crossings

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "base": self.base,
            "is_normal": self.is_normal,
            "is_computable": self.is_computable,
            "eml_class": str(self.eml_class()),
            "eml_depth": self.eml_depth if self.eml_depth != EML_INF else "inf",
            "construction": self.construction,
        }


NORMAL_NUMBERS = [
    NormalNumber(
        "Champernowne C₁₀", 10, True, True, 2.0,
        "Concatenate naturals: 0.123456789101112... — provably normal in base 10",
    ),
    NormalNumber(
        "Copeland-Erdős", 10, True, True, 2.0,
        "Concatenate primes: 0.2357111317... — provably normal in base 10",
    ),
    NormalNumber(
        "π (conjectured)", 10, True, True, 3.0,
        "π is conjectured normal but not proved; digits computed via EML-3 arctan/BBP",
    ),
    NormalNumber(
        "Typical real (Borel)", 10, True, False, EML_INF,
        "Almost every real is normal; a generic normal real has no finite description → EML-∞",
    ),
    NormalNumber(
        "Liouville constant", 10, False, True, 2.0,
        "L = Σ 10^{-n!} is computable but NOT normal (digits 0 almost always)",
    ),
]


# ---------------------------------------------------------------------------
# EML Computability Theorem
# ---------------------------------------------------------------------------

@dataclass
class EMLComputabilityTheorem:
    """
    Theorem: A real number α is computable iff there exists k < ∞ such that
    the digit-expansion function n ↦ d_n(α) is EML-k as a function on ℤ≥0.

    Equivalently:
    - Computable real ↔ EML-finite digit function
    - Martin-Löf random ↔ EML-∞ digit function (no finite depth suffices)
    - The EML depth of α = min k such that digits are EML-k computable

    This bridges computability theory (Turing, Church) with EML complexity.
    """
    statement: str = (
        "A real α is computable iff its digit function n↦d_n(α) is EML-finite. "
        "α is Martin-Löf random iff its digit function is EML-∞."
    )

    proof_sketch: str = (
        "Forward: if α computable, digit algorithm is a finite program → "
        "can be expressed as EML tree of bounded depth (each arithmetic op is EML-1 or EML-2). "
        "Backward: if digit function is EML-k for some k, then each digit d_n = "
        "round(EML_tree(n) mod base) is computable from n → α is computable. "
        "For Martin-Löf random α: any EML-finite f would give a computable approximation, "
        "but ML-random sequences are not computable → contradiction → must be EML-∞."
    )

    examples: list[dict] = field(default_factory=lambda: [
        {"real": "e", "eml_depth": 1, "why": "e = exp(1), direct EML-1 atom"},
        {"real": "ln 2", "eml_depth": 2, "why": "ln(2) = EML-2 (ln gate on integer)"},
        {"real": "√2", "eml_depth": 2, "why": "exp(½·ln 2) = EML-2"},
        {"real": "π", "eml_depth": 3, "why": "arctan via BBP → EML-3 oscillatory series"},
        {"real": "Champernowne", "eml_depth": 2, "why": "digit(n) = rational arithmetic → EML-2"},
        {"real": "Chaitin Ω", "eml_depth": "∞", "why": "ML-random, no computable digit extraction"},
        {"real": "generic Borel normal", "eml_depth": "∞", "why": "Almost all reals → EML-∞"},
    ])

    def to_dict(self) -> dict:
        return {
            "theorem": "EML Computability Theorem",
            "statement": self.statement,
            "proof_sketch": self.proof_sketch,
            "examples": self.examples,
        }


# ---------------------------------------------------------------------------
# EML Taxonomy for Algorithmic Randomness
# ---------------------------------------------------------------------------

ALGO_RANDOM_EML_TAXONOMY: dict[str, dict] = {
    "martin_lof_random_sequence": {
        "eml_depth": "∞",
        "description": "Passes all computable statistical tests",
        "reason": "No finite EML tree generates a truly random sequence",
        "examples": ["Chaitin Ω digits", "fair coin flips", "QRNG output"],
    },
    "chaitin_omega": {
        "eml_depth": "∞",
        "description": "Halting probability Ω = Σ_{p halts} 2^{-|p|}",
        "reason": "ML-random by definition; left-computable but not right-computable",
        "examples": ["Ω for universal Turing machine"],
    },
    "normal_number_generic": {
        "eml_depth": "∞",
        "description": "Typical Borel-normal real — no explicit construction",
        "reason": "No EML-finite description; generic element of full-measure set",
        "examples": ["Lebesgue-a.e. real"],
    },
    "computable_real_eml1": {
        "eml_depth": 1,
        "description": "Computable reals expressible via exp",
        "reason": "e = exp(1), exp(r) for rational r — single EML-1 atom",
        "examples": ["e", "exp(1/2)", "exp(π) (conjectural EML-3)"],
    },
    "computable_real_eml2": {
        "eml_depth": 2,
        "description": "Algebraic reals and simple transcendentals",
        "reason": "exp(rational·ln(integer)) = rational power — EML-2",
        "examples": ["√2", "ln 2", "Champernowne", "Liouville"],
    },
    "computable_real_eml3": {
        "eml_depth": 3,
        "description": "Transcendentals requiring oscillatory series",
        "reason": "π via arctan = EML-3; erf^{-1} etc.",
        "examples": ["π", "erf^{-1}(1/2)", "Catalan constant G (conjectured EML-3)"],
    },
    "pseudorandom_sequence": {
        "eml_depth": 2,
        "description": "Deterministic sequence that passes statistical tests",
        "reason": "Generated by EML-2 recurrence (LCG, Mersenne); statistically random but EML-finite",
        "examples": ["LCG output", "Mersenne Twister", "PRNG with seed"],
    },
    "normal_champernowne": {
        "eml_depth": 2,
        "description": "Champernowne's number — computable and normal",
        "reason": "Digit function n↦d_n is rational arithmetic → EML-2, but distribution is uniform",
        "examples": ["0.123456789101112...", "Copeland-Erdős"],
    },
    "kolmogorov_complexity_k": {
        "eml_depth": "∞",
        "description": "Kolmogorov complexity K(x) as a function of x",
        "reason": "K is non-computable (halting problem); its values jump infinitely → EML-∞",
        "examples": ["K({0,1}^n)", "K(π restricted to n digits)"],
    },
    "eml_depth_as_complexity": {
        "eml_depth": "varies",
        "description": "EML depth as a computable proxy for Kolmogorov complexity",
        "reason": "EML-k depth is computable (bounded search); K(x) is not. EML depth ≈ log(K(x))",
        "examples": ["EML-2 reals: K ≈ O(log n)", "EML-∞ reals: K ≈ n (incompressible)"],
    },
}


# ---------------------------------------------------------------------------
# Main analysis function
# ---------------------------------------------------------------------------

def analyze_algo_random_eml() -> dict:
    """Run full Session 69 analysis."""

    # 1. Computable reals classification
    computable_reals_report = [r.to_dict() for r in COMPUTABLE_REALS]

    # 2. Martin-Löf tests on example sequences
    import random
    rng = random.Random(42)

    # Truly "random" (PRNG approximation)
    seq_random = [rng.randint(0, 1) for _ in range(1000)]

    # Structured: alternating 0,1
    seq_alternating = [i % 2 for i in range(1000)]

    # Champernowne binary digits
    champernowne_str = "".join(bin(k)[2:] for k in range(1, 300))
    seq_champernowne = [int(c) for c in champernowne_str[:1000]]

    ml_tests = {
        "prng_sequence": {
            "description": "PRNG (Python random, seed=42) — EML-2 structure",
            "freq": MartinLofRandomness.frequency_test(seq_random),
            "runs": MartinLofRandomness.runs_test(seq_random),
            "block_entropy": MartinLofRandomness.block_entropy_test(seq_random),
            "classified_eml": str(MartinLofRandomness.classify_sequence(seq_random)),
        },
        "alternating_sequence": {
            "description": "010101... — EML-0 (constant period-2)",
            "freq": MartinLofRandomness.frequency_test(seq_alternating),
            "runs": MartinLofRandomness.runs_test(seq_alternating),
            "block_entropy": MartinLofRandomness.block_entropy_test(seq_alternating),
            "classified_eml": str(MartinLofRandomness.classify_sequence(seq_alternating)),
        },
        "champernowne_binary": {
            "description": "Binary Champernowne — EML-2 (computable normal)",
            "freq": MartinLofRandomness.frequency_test(seq_champernowne),
            "runs": MartinLofRandomness.runs_test(seq_champernowne),
            "block_entropy": MartinLofRandomness.block_entropy_test(seq_champernowne),
            "classified_eml": str(MartinLofRandomness.classify_sequence(seq_champernowne)),
        },
    }

    # 3. Chaitin Omega
    omega_report = ChaitinOmega.lower_bound(max_prog_len=8)
    omega_eml = ChaitinOmega.eml_classification()

    # 4. Normal numbers
    normal_numbers_report = [n.to_dict() for n in NORMAL_NUMBERS]

    # Frequency deviation for Champernowne (first 500 decimal digits via string)
    champ_digits = [int(c) for c in "".join(str(k) for k in range(1, 200))[:500] if c.isdigit()]
    n_champernowne = NormalNumber("Champernowne", 10, True, True, 2.0, "")
    deviation_sample = n_champernowne.frequency_deviation(champ_digits, 1)[:50]
    zero_crossings = n_champernowne.zero_crossings(champ_digits, 1)

    # 5. Computability theorem
    theorem = EMLComputabilityTheorem()

    # 6. Taxonomy
    taxonomy = ALGO_RANDOM_EML_TAXONOMY

    return {
        "session": 69,
        "title": "Algorithmic Randomness in EML",
        "key_theorem": theorem.to_dict(),
        "computable_reals": computable_reals_report,
        "martin_lof_tests": ml_tests,
        "chaitin_omega": {
            **omega_report,
            "eml_class": str(omega_eml),
        },
        "normal_numbers": normal_numbers_report,
        "champernowne_analysis": {
            "digits_analyzed": len(champ_digits),
            "zero_crossings_digit_1": zero_crossings,
            "zero_crossings_comment": (
                "Many crossings → frequency oscillates around 1/10 → EML-∞ behavior in limit; "
                "but Champernowne itself is EML-2 because digit function is computable"
            ),
            "deviation_sample_first_50": [round(d, 4) for d in deviation_sample],
        },
        "taxonomy": taxonomy,
        "eml_depth_summary": {
            "EML-0": "Periodic sequences (010101...), ultimately periodic binary strings",
            "EML-1": "e and its rational-argument evaluations",
            "EML-2": "Algebraic reals (√2, ∛3), ln(rational), Champernowne, Copeland-Erdős, PRNGs",
            "EML-3": "π, erf^{-1}, oscillatory transcendentals",
            "EML-∞": "Martin-Löf random reals, Chaitin Ω, Kolmogorov complexity K(x), generic Borel normals",
        },
        "connections": {
            "to_session_40": "EML Weierstrass → EML-finite functions are dense; random functions are EML-∞",
            "to_session_57": "Boltzmann factor = EML-1 deterministic; thermal noise = EML-∞",
            "to_session_62": "NS blowup = EML-∞ at T*; same barrier as algorithmic randomness",
            "to_turing": "Halting problem undecidability ↔ EML-∞ of Chaitin Ω",
        },
    }


if __name__ == "__main__":
    result = analyze_algo_random_eml()
    print(json.dumps(result, indent=2, default=str))
