/**
 * superbest.js — SuperBEST routing engine for browser
 * Canonical v5.3 routing table synced from python/monogate/superbest.py.
 * Positive headline: 14n / 80.8% vs 73n naive.
 * General headline: 16n / 74.2% vs 62n naive over the 8-op basket.
 * <5KB, zero dependencies.
 */

// ── Routing table ─────────────────────────────────────────────────────────────
export const TABLE = {
  exp:    { op:"EML",  nodes:1,  domain:"all x",   construction:"eml(x,1)",               emlNodes:1  },
  expNeg: { op:"DEML", nodes:1,  domain:"all x",   construction:"deml(x,1)",              emlNodes:1  },
  ln:     { op:"EXL",  nodes:1,  domain:"x>0",     construction:"exl(0,x)",               emlNodes:3  },
  div:    { op:"EXL/ELSb", nodes:2, domain:"x,y>0", construction:"elsb(exl(0,x),y)",      emlNodes:15 },
  recip:  { op:"ELSb", nodes:1,    domain:"x>0",     construction:"elsb(0,x)",             emlNodes:5  },
  neg:    { op:"EXL/DEML", nodes:2, domain:"all x",  construction:"exl(0,deml(x,1))",      emlNodes:9  },
  mul:    { op:"EPL/ELMl", nodes:1, domain:"x,y>0",  construction:"elml(ln(x),y)",         emlNodes:13 },
  sub:    { op:"LEdiv/EML", nodes:2, domain:"all x,y", construction:"lediv(x,eml(y,1))",   emlNodes:5  },
  pow:    { op:"EPL/ELMl", nodes:1, domain:"x>0",    construction:"epl(n,x)",              emlNodes:3  },
  add:    { op:"LEdiv/DEML", nodes:2, domain:"all x,y", construction:"lediv(x,deml(y,1))", emlNodes:11 },
  addGen: { op:"EML",  nodes:11, domain:"all x,y", construction:"EML single-op",          emlNodes:11 },
  sqrt:   { op:"EPL",  nodes:1,  domain:"x>0",     construction:"epl(0.5,x)",             emlNodes:8  },
  sin:    { op:"EXL",  nodes:63, domain:"all x",   construction:"8-term Taylor (EXL pow)", emlNodes:245},
  cos:    { op:"EXL",  nodes:63, domain:"all x",   construction:"8-term Taylor (EXL pow)", emlNodes:245},
  abs:    { op:"EPL",  nodes:2,  domain:"all x",   construction:"2-node EPL construction", emlNodes:5  },
};

// ── Node costs (SuperBEST v5.3 canonical sync) ────────────────────────────────
export const COSTS = {
  exp:1, ln:1, div:2, pow:1, mul:1, sub:2, neg:2, add:2, sqrt:1,
  sin:63, cos:63, recip:1, abs:2,
};

// ── EML single-operator baseline ──────────────────────────────────────────────
export const EML_COSTS = {
  exp:1, ln:3, div:15, pow:3, mul:13, sub:5, neg:9, add:11, sqrt:8,
  sin:245, cos:245, recip:5, abs:5,
};

// ── Operator family for coloring ──────────────────────────────────────────────
export const FAMILY = {
  exp:"EML", ln:"EXL", div:"EXL/ELSb", pow:"EPL/ELMl", mul:"EPL/ELMl",
  sub:"LEdiv/EML", neg:"EXL/DEML", add:"LEdiv/DEML", sqrt:"EPL", sin:"EXL",
  cos:"EXL", recip:"ELSb", abs:"EPL",
};

/** Count SuperBEST nodes for a {opName: count} map. */
export function nodeCount(opCounts) {
  let total = 0;
  for (const [op, count] of Object.entries(opCounts)) {
    total += (COSTS[op] ?? 1) * count;
  }
  return total;
}

/** Count EML-baseline nodes for a {opName: count} map. */
export function emlNodeCount(opCounts) {
  let total = 0;
  for (const [op, count] of Object.entries(opCounts)) {
    total += (EML_COSTS[op] ?? 1) * count;
  }
  return total;
}

/** Savings percentage: (1 - optimized/original) × 100 */
export function savings(original, optimized) {
  if (!original) return 0;
  return Math.round((1 - optimized / original) * 100);
}

/** Operator family for a named op. */
export function operatorOf(opName) {
  return FAMILY[opName] ?? "EML";
}

// ── Code export ───────────────────────────────────────────────────────────────

const LANG_FMT = {
  python: {
    lineComment: "#",
    fn:   (name, args, body) => `def ${name}_best(${args}):\n${body}\n`,
    ln:   "math.log", exp: "math.exp",
    ret:  "    return ",
    var:  (n, v) => `    ${n} = ${v}\n`,
    header: (expr, eml, best) =>
      `# SuperBEST: ${expr} — ${eml}n (EML) → ${best}n (SuperBEST)\n# Generated by monogate.dev\nimport math\n\n`,
  },
  js: {
    lineComment: "//",
    fn:   (name, args, body) => `function ${name}_best(${args}) {\n${body}}\n`,
    ln:   "Math.log", exp: "Math.exp",
    ret:  "  return ",
    var:  (n, v) => `  const ${n} = ${v};\n`,
    header: (expr, eml, best) =>
      `// SuperBEST: ${expr} — ${eml}n (EML) → ${best}n (SuperBEST)\n// Generated by monogate.dev\n\n`,
  },
  glsl: {
    lineComment: "//",
    fn:   (name, args, body) => `float ${name}_best(${args}) {\n${body}}\n`,
    ln:   "log", exp: "exp",
    ret:  "    return ",
    var:  (n, v) => `    float ${n} = ${v};\n`,
    header: (expr, eml, best) =>
      `// SuperBEST: ${expr} — ${eml}n (EML) -> ${best}n (SuperBEST)\n// Generated by monogate.dev\n\n`,
    argType: "float",
  },
  hlsl: {
    lineComment: "//",
    fn:   (name, args, body) => `float ${name}_best(${args}) {\n${body}}\n`,
    ln:   "log", exp: "exp",
    ret:  "    return ",
    var:  (n, v) => `    float ${n} = ${v};\n`,
    header: (expr, eml, best) =>
      `// SuperBEST: ${expr} — ${eml}n (EML) -> ${best}n (SuperBEST)\n// Generated by monogate.dev\n\n`,
    argType: "float",
  },
  rust: {
    lineComment: "//",
    fn:   (name, args, body) => `fn ${name}_best(${args}) -> f64 {\n${body}}\n`,
    ln:   ".ln()", exp: ".exp()",
    ret:  "    ",
    var:  (n, v) => `    let ${n} = ${v};\n`,
    header: (expr, eml, best) =>
      `// SuperBEST: ${expr} — ${eml}n (EML) -> ${best}n (SuperBEST)\n// Generated by monogate.dev\n\n`,
    rust: true,
  },
  c: {
    lineComment: "//",
    fn:   (name, args, body) => `double ${name}_best(${args}) {\n${body}}\n`,
    ln:   "log", exp: "exp",
    ret:  "    return ",
    var:  (n, v) => `    double ${n} = ${v};\n`,
    header: (expr, eml, best) =>
      `// SuperBEST: ${expr} — ${eml}n (EML) -> ${best}n (SuperBEST)\n// Generated by monogate.dev\n#include <math.h>\n\n`,
  },
};

function callFn(fmt, name, ...args) {
  if (fmt.rust) return `${args[0]}${name}()`;
  return `${name}(${args.join(", ")})`;
}

function ln(fmt, v) {
  return fmt.rust ? `${v}.ln()` : `${fmt.ln}(${v})`;
}
function expp(fmt, v) {
  return fmt.rust ? `${v}.exp()` : `${fmt.exp}(${v})`;
}

// Build code for known operation+language combos
function buildBody(op, fmt, a = "x", b = "y") {
  const { var: mkVar, ret } = fmt;
  const zero = fmt.rust ? "0f64" : "0.0";
  const one  = fmt.rust ? "1f64" : "1.0";

  switch (op) {
    case "mul": // canonical display: elml(ln(x), y), x,y>0
      return ret + `${a} * ${b} ${fmt.lineComment} EPL/ELMl canonical positive-domain route [1n]\n`;
    case "sub": // lediv(x, eml(y,1)): x-y for all reals
      return (
        mkVar("_exp_y", `${expp(fmt, b)} ${fmt.lineComment} EML: exp(y) [1n]`) +
        ret + `${a} - ${ln(fmt, "_exp_y")} ${fmt.lineComment} LEdiv: x-y [1n]\n`
      );
    case "neg": // exl(0, deml(x,1)): -x all domain
      return (
        mkVar("_t", `${expp(fmt, `-${a}`)} ${fmt.lineComment} DEML: exp(-x) [1n]`) +
        ret + `${expp(fmt, zero)} * ${ln(fmt, "_t")} ${fmt.lineComment} EXL: -x [1n]\n`
      );
    case "div": // exl(0,x) then elsb(ln(x),y): x/y
      return (
        mkVar("_ln_x", `${ln(fmt, a)} ${fmt.lineComment} EXL: ln(x) [1n]`) +
        ret + `${expp(fmt, `_ln_x - ${ln(fmt, b)}`)} ${fmt.lineComment} ELSb: x/y [1n]\n`
      );
    case "recip": // elsb(0,x): 1/x
      return ret + `${expp(fmt, `${zero} - ${ln(fmt, a)}`)} ${fmt.lineComment} ELSb: 1/x [1n]\n`;
    case "pow": // epl(n,x): x^n
      return ret + `${expp(fmt, `${b} * ${ln(fmt, a)}`)} ${fmt.lineComment} EPL/ELMl: x^n [1n]\n`;
    case "add": // lediv(x, deml(y,1)): x+y for all reals
      return (
        mkVar("_exp_neg_y", `${expp(fmt, `-${b}`)} ${fmt.lineComment} DEML: exp(-y) [1n]`) +
        ret + `${a} - ${ln(fmt, "_exp_neg_y")} ${fmt.lineComment} LEdiv: x+y [1n]\n`
      );
    case "ln": // exl(0, x)
      return ret + `${expp(fmt, zero)} * ${ln(fmt, a)} ${fmt.lineComment} EXL: ln(x) [1n]\n`;
    case "exp": // eml(x, 1)
      return ret + `${expp(fmt, a)} - ${ln(fmt, one)} ${fmt.lineComment} EML: exp(x) [1n]\n`;
    default:
      return ret + `0 ${fmt.lineComment} TODO: ${op} construction\n`;
  }
}

function fmtArgs(fmt, ops) {
  const unary = ["neg", "ln", "exp", "recip", "sqrt", "abs"];
  const isUnary = unary.includes(ops);
  if (fmt.argType) {
    return isUnary ? `${fmt.argType} x` : `${fmt.argType} x, ${fmt.argType} y`;
  }
  if (fmt.rust) {
    return isUnary ? "x: f64" : "x: f64, y: f64";
  }
  return isUnary ? "x" : "x, y";
}

/**
 * Generate production-ready code for a SuperBEST operation.
 * @param {string} op — operation name (mul, sub, neg, div, pow, add, ln, exp, recip)
 * @param {string} lang — python | js | glsl | hlsl | rust | c
 * @returns {string} formatted source code
 */
export function exportCode(op, lang) {
  const fmt = LANG_FMT[lang];
  if (!fmt) return `// Language '${lang}' not supported`;
  const entry = TABLE[op];
  if (!entry) return `// Operation '${op}' not in SuperBEST table`;

  const header = fmt.header(op, entry.emlNodes, entry.nodes);
  const args   = fmtArgs(fmt, op);
  const body   = buildBody(op, fmt, "x", "y");
  const domNote = entry.domain !== "all x"
    ? `${fmt.lineComment} Domain: ${entry.domain}\n`
    : "";
  return header + domNote + fmt.fn(op, args, body);
}

// ── Benchmark presets ─────────────────────────────────────────────────────────

export const BENCHMARKS = [
  { id:"exp",     label:"exp(x)",           ops:{ exp:1 } },
  { id:"ln",      label:"ln(x)",            ops:{ ln:1  } },
  { id:"div",     label:"div(x,y)",         ops:{ div:1 } },
  { id:"recip",   label:"recip(x)",         ops:{ recip:1 } },
  { id:"neg",     label:"neg(x)",           ops:{ neg:1 } },
  { id:"mul",     label:"mul(x,y)",         ops:{ mul:1 } },
  { id:"sub",     label:"sub(x,y)",         ops:{ sub:1 } },
  { id:"pow3",    label:"pow(x,3)",         ops:{ pow:1 } },
  { id:"add",     label:"add(x,y)",         ops:{ add:1 } },
  { id:"sqrt",    label:"sqrt(x)",          ops:{ sqrt:1} },
  { id:"sin",     label:"sin(x)",           ops:{ sin:1 } },
  { id:"cos",     label:"cos(x)",           ops:{ cos:1 } },
  { id:"sigmoid", label:"sigmoid(x)",       ops:{ neg:1, exp:1, add:1, recip:1 } },
  { id:"tanh",    label:"tanh(x)",          ops:{ mul:1, exp:1, sub:1, add:1, div:1 } },
  { id:"gelu",    label:"gelu(x)",          ops:{ mul:1, pow:1, mul:1, add:1, mul:1 } },
  { id:"gaussian",label:"gaussian(x)",      ops:{ neg:1, mul:1, pow:1, exp:1 } },
  { id:"sincos",  label:"sin(x)+cos(x)",    ops:{ sin:1, cos:1, add:1 } },
  { id:"sincosP", label:"sin(x)*cos(x)",    ops:{ sin:1, cos:1, mul:1 } },
  { id:"pow3add", label:"pow(x,3)+2*x",     ops:{ pow:1, mul:1, add:1 } },
  { id:"expsin",  label:"exp(-x)*sin(x)",   ops:{ neg:1, exp:1, sin:1, mul:1 } },
  { id:"lograt",  label:"ln(x+1)/x",        ops:{ add:1, ln:1, div:1 } },
  { id:"softmax", label:"softmax term",     ops:{ exp:1, div:1 } },
  { id:"hyperbolic",label:"cosh+sinh",      ops:{ exp:2, add:1, sub:1, mul:2, div:2 } },
  { id:"rational",label:"(1+x)/(1-x)",     ops:{ add:1, sub:1, div:1 } },
  { id:"poly5",   label:"x^5+x^3+x",       ops:{ pow:2, mul:2, add:2 } },
];

/** Run all benchmarks, return array of result objects. */
export function runBenchmarks() {
  return BENCHMARKS.map(b => {
    const best = nodeCount(b.ops);
    const eml  = emlNodeCount(b.ops);
    const pct  = savings(eml, best);
    return { ...b, best, eml, savings: pct };
  });
}
