-- Candidate-only EML Atlas Annex stubs.
-- Generated by python/scripts/eml_atlas_annex.py.
-- These are review targets, not checked proof claims.

namespace Monogate
namespace EML
namespace AtlasAnnex

def bose_boundary_candidate_obligation : String :=
  "Bose-Einstein denominator: candidate-only Atlas identity witness target"

def constants_zero_and_e_candidate_obligation : String :=
  "constants e and 0: candidate-only Atlas identity witness target"

def euler_null_state_candidate_obligation : String :=
  "Euler null state: candidate-only Atlas identity witness target"

def exp_from_eml_candidate_obligation : String :=
  "exp(x): candidate-only Atlas identity witness target"

def fermi_boundary_candidate_obligation : String :=
  "Fermi-Dirac denominator: candidate-only Atlas identity witness target"

end AtlasAnnex
end EML
end Monogate
