import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildEvidencePacket, validateEvidencePacket } from "../src/ir.js";

const OUT_DIR = new URL("../../reports/evidence_packets/", import.meta.url);

const CASES = [
  { id: "exp_shared", expression: "exp(x) + exp(x)" },
  { id: "domain_guards", expression: "ln(x) + sqrt(y)" },
  { id: "exp_ratio", expression: "exp(x) / exp(y)" },
  { id: "trig_pair", expression: "sin(x) + cos(x)" },
  { id: "saturation_probe", expression: "tanh(x*x)" },
];

await mkdir(OUT_DIR, { recursive: true });

const index = {
  schema_version: "monogate.eml_ir.evidence_corpus.v1",
  generated_at: "2026-05-26",
  packet_count: CASES.length,
  packets: [],
  boundaries: {
    sampled_evidence_only: true,
    formal_verification_claim: false,
    compiler_release_claim: false,
  },
};

for (const item of CASES) {
  const packet = buildEvidencePacket(item.expression);
  const validation = validateEvidencePacket(packet);
  if (!validation.ok) {
    throw new Error(`${item.id} failed validation: ${validation.errors.join("; ")}`);
  }
  const filename = `${item.id}.json`;
  await writeFile(new URL(filename, OUT_DIR), `${JSON.stringify(packet, null, 2)}\n`);
  index.packets.push({
    id: item.id,
    expression: item.expression,
    filename,
    packet_hash: packet.packet_hash,
    research_status: packet.research_status,
  });
}

await writeFile(new URL("index.json", OUT_DIR), `${JSON.stringify(index, null, 2)}\n`);
await writeFile(
  join(OUT_DIR.pathname, "README.md"),
  [
    "# EML IR Evidence Packet Corpus",
    "",
    "Generated by `node lib/scripts/generate_ir_evidence_corpus.mjs`.",
    "",
    "| id | expression | status | packet hash |",
    "|---|---|---|---|",
    ...index.packets.map((p) => `| ${p.id} | \`${p.expression}\` | ${p.research_status.labels.join(" / ")} | \`${p.packet_hash}\` |`),
    "",
    "These packets are sampled/internal evidence only, not formal verification claims.",
    "",
  ].join("\n"),
);

console.log("IR_EVIDENCE_CORPUS_OK");
